twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates/bundles/SyliusGridBundle': SyliusGrid
        '%kernel.project_dir%/templates/admin': SyliusAdmin

when@test:
    twig:
        strict_variables: true
