admin_dashboard:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'admin/dashboard.html.twig'

admin_dashboard_trailing:
    path: /admin/
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'admin/dashboard.html.twig'
